language: python

python:
    - "2.7"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then pip --quiet install git+https://github.com/webitup/pil-py3k-mirror.git; fi
    - pip --quiet install pil
    - sudo apt-get --quiet=2 install perceptualdiff

script:
    - ./test/test.py
